### ISSUE TITLE
Issue while installation

### ISSUE THREAD

**Issue by Nittonull** [zAbuQasem/PwnShell#1]
Hi buddy,

I got this error while i ran this command 

pip3 install -r requirements.txt

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
crackmapexec 5.1.1 requires pylnk3<0.4.0,>=0.3.0, but you have pylnk3 0.4.2 which is incompatible.

**Comment by zAbuQasem** [comment]
This seems to be a problem with crackmapexec dependencies try upgrading the tool or remove the `pylnk3` then install it using this command `pip install pylnk3==0.3.0`

But before doing the fix can you confirm if my tool is working?
Because the error should have no effect on it.

**Comment by Nittonull** [comment]
Yeah, thanks for the quick response, tool is working. Looks like crackmap having issues,

**Comment by zAbuQasem** [comment]
You're welcome 🙂
